[workspace]
resolver = "2"

members = [
    "rat-cursor",
    "rat-event",
    "rat-focus",
    "rat-ftable",
    "rat-menu",
    "rat-popup",
    "rat-reloc",
    "rat-salsa",
    "rat-scrolled",
    "rat-text",
    "rat-theme",
    "rat-widget",
]