[package]
name = "rat-ftable"
version = "0.28.1"
edition = "2021"
description = "ratatui table widget for large data"
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/rat-ftable"
readme = "readme.md"
keywords = ["ratatui", "table", "large"]
categories = ["command-line-interface"]
exclude = [".idea/*", ".gitignore", "ftable.gif"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
absolute_paths_not_starting_with_crate = "warn"
# box_pointers = "warn"
elided_lifetimes_in_paths = "warn"
explicit_outlives_requirements = "warn"
keyword_idents = "warn"
macro_use_extern_crate = "warn"
meta_variable_misuse = "warn"
missing_abi = "warn"
# NOT_ACCURATE: missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "allow"
non_ascii_idents = "warn"
noop_method_call = "warn"
# NO: or_patterns_back_compat = "warn"
semicolon_in_expressions_from_macros = "warn"
# NOT_ACCURATE: single_use_lifetimes = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unreachable_pub = "warn"
# unsafe_code: = "warn"
unsafe_op_in_unsafe_fn = "warn"
unstable_features = "warn"
# NO: unused_crate_dependencies = "warn"
# NO: unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
# NO: unused_results = "warn"
variant_size_differences = "warn"

[features]
unstable-widget-ref = [
    "ratatui/unstable-widget-ref",
    "rat-scrolled/unstable-widget-ref",
]

[dependencies]
crossterm = "0.28"
ratatui = { version = "0.29" }
log = "0.4"

rat-event = { version = "0.26", path = "../rat-event" }
rat-reloc = { version = "0.2", path = "../rat-reloc" }
rat-cursor = { version = "0.25", path = "../rat-cursor" }
rat-focus = { version = "0.29", path = "../rat-focus" }
rat-scrolled = { version = "0.27", path = "../rat-scrolled" }

[dev-dependencies]
fern = "0.7"
humantime = "2.1"
rand = "0.8.5"
anyhow = "1.0"
format_num_pattern = "0.9.2"
unicode-segmentation = "1.11"
