#==================================================================================================
[workspace]
resolver = "2"

members = [
    "rat-cursor",
    "rat-event",
    "rat-focus",
    "rat-ftable",
    "rat-menu",
    "rat-markdown",
    "rat-popup",
    "rat-reloc",
    "rat-salsa",
    "rat-scrolled",
    "rat-text",
    "rat-theme",
    "rat-theme2",
    "rat-widget",
    "rat-dialog",
]
#==================================================================================================
[workspace.package]
version = "2025.9.231358"
edition = "2024"
#==================================================================================================