[package]
name = "rat-text"
version = "0.29.0"
edition = "2021"
authors = ["thscharler <thscharler@gmail.com>"]
description = "ratatui text input widgets"
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/rat-text"
readme = "readme.md"
keywords = ["ratatui", "widget", "text"]
categories = ["command-line-interface"]
exclude = [".idea/*", ".gitignore"]

[lints.clippy]
collapsible_else_if = "allow"
collapsible_if = "allow"
if_same_then_else = "allow"
comparison_chain = "allow"

[lints.rust]
absolute_paths_not_starting_with_crate = "warn"
# box_pointers = "warn"
elided_lifetimes_in_paths = "warn"
explicit_outlives_requirements = "warn"
keyword_idents = "warn"
macro_use_extern_crate = "warn"
meta_variable_misuse = "warn"
missing_abi = "warn"
# NOT_ACCURATE: missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "allow"
non_ascii_idents = "warn"
noop_method_call = "warn"
# NO: or_patterns_back_compat = "warn"
semicolon_in_expressions_from_macros = "warn"
# NOT_ACCURATE: single_use_lifetimes = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unreachable_pub = "warn"
# unsafe_code: = "warn"
unsafe_op_in_unsafe_fn = "warn"
unstable_features = "warn"
# NO: unused_crate_dependencies = "warn"
# NO: unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
# NO: unused_results = "warn"
variant_size_differences = "warn"

[features]
unstable-widget-ref = ["ratatui/unstable-widget-ref"]

[dependencies]
ratatui = { version = "0.29", path = "../ratatui" }
crossterm = "0.28"
ropey = "1.6.1"
iset = "0.3"
pure-rust-locales = "0.8"
unicode-segmentation = "1.11"
unicode-width = "0.2"
unicode-display-width = "0.3"
rust_decimal = "1.34"
rust_decimal_macros = "1.34"
chrono = { version = "0.4", features = ["unstable-locales"] }
memchr = "2.7.2"
format_num_pattern = "0.9"
log = "0.4"
dyn-clone = "1.0.17"

rat-event = { version = "0.26", path = "../rat-event" }
rat-reloc = { version = "0.2", path = "../rat-reloc" }
rat-cursor = { version = "0.25", path = "../rat-cursor" }
rat-focus = { version = "0.28", path = "../rat-focus" }
rat-scrolled = { version = "0.27", path = "../rat-scrolled" }

[dev-dependencies]
fern = "0.7"
anyhow = "1.0"
lorem-rustum = "0.0.5"








