[package]
name = "rat-popup"
version = "0.28.3"
edition = "2021"
authors = ["thscharler <thscharler@gmail.com>"]
description = "ratatui popup semi-window widget"
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/rat-popup"
readme = "readme.md"
keywords = ["ratatui", "popup"]
categories = ["command-line-interface"]
exclude = [".idea/*", ".gitignore"]

[features]
unstable-widget-ref = ["ratatui/unstable-widget-ref"]

[dependencies]
ratatui = { version = "0.29", features = ["unstable-rendered-line-info"] }
crossterm = "0.28"
log = "0.4"

rat-event = { version = "1.0" }
rat-reloc = { version = "1.0" }
rat-focus = { version = "0.30" }
rat-scrolled = { version = "1.0" }
rat-cursor = { version = "1.0" }

[dev-dependencies]
fern = "0.7"
anyhow = "1.0"
unicode-segmentation = "1.11"
