[package]
name = "rat-salsa"
version = "0.24.2"
authors = ["thscharler <thscharler@gmail.com>"]
edition = "2021"
description = "ratatui widgets and a crossterm event-loop"
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/rat-salsa"
readme = "readme.md"
keywords = ["ratatui", "input", "event-loop"]
categories = ["command-line-interface"]
exclude = [".idea/*", ".gitignore", "files.gif", "mdedit.gif"]

[lints.rust]
absolute_paths_not_starting_with_crate = "warn"
# box_pointers = "warn"
elided_lifetimes_in_paths = "warn"
explicit_outlives_requirements = "warn"
keyword_idents = "warn"
macro_use_extern_crate = "warn"
meta_variable_misuse = "warn"
missing_abi = "warn"
# NOT_ACCURATE: missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "allow"
non_ascii_idents = "warn"
noop_method_call = "warn"
# NO: or_patterns_back_compat = "warn"
semicolon_in_expressions_from_macros = "warn"
# NOT_ACCURATE: single_use_lifetimes = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unreachable_pub = "warn"
# unsafe_code: = "warn"
unsafe_op_in_unsafe_fn = "warn"
unstable_features = "warn"
# NO: unused_crate_dependencies = "warn"
# NO: unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
# NO: unused_results = "warn"
variant_size_differences = "warn"

[dependencies]
crossbeam = "0.8"
crossterm = "0.28"
log = "0.4"
ratatui = { version = "0.28" }

rat-widget = { version = "0.16", path = "../rat-widget" }

[dev-dependencies]
fern = "0.6"
humantime = "2.1"
anyhow = "1.0"
rat-theme = { version = "0.12", path = "../rat-theme" }
directories-next = "2.0.0"
sysinfo = "0.31"
pulldown-cmark = "0.12.0"
ropey = "1.6.1"
cli-clipboard = "0.4.0"
unicode-segmentation = "1.11"
textwrap = "0.16"
configparser = { version = "3.1.0", features = ["indexmap"] }
rand = "0.8.5"