[package]
name = "rat-reloc"
version = "1.0.0"
edition = "2021"
description = "relocate widgets after rendering"
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/rat-salsa"
readme = "readme.md"
keywords = ["ratatui", "widget", "clip"]
categories = ["command-line-interface"]
exclude = [".idea/*", ".gitignore"]

[dependencies]
ratatui = { version = "0.29" }
log = "0.4"