[package]
name = "rat-dialog"
version = "0.1.0"
authors = ["thscharler <thscharler@gmail.com>"]
edition = "2021"
description = "stacked dialog windows"
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/rat-salsa"
readme = "readme.md"
keywords = ["ratatui", ]
categories = ["command-line-interface"]
exclude = [".idea/*", ".gitignore", "files.gif", "mdedit.gif"]

[features]
default = []

[dependencies]
crossbeam = "0.8"
crossterm = "0.28"
log = "0.4"
ratatui = { version = "0.29" }

rat-widget = { version = "1.0", path = "../rat-widget" }
rat-salsa = { version = "1.0", path = "../rat-salsa" }

[dev-dependencies]
anyhow = "1.0"
fern = "0.7"
dirs = "6.0"

rat-theme2 = { version = "0.28", path = "../rat-theme2" }

