[package]
name = "rat-salsa"
version = "0.30.1"
authors = ["thscharler <thscharler@gmail.com>"]
edition = "2021"
description = "ratatui widgets and a crossterm event-loop"
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/rat-salsa"
readme = "readme.md"
keywords = ["ratatui", "input", "event-loop"]
categories = ["command-line-interface"]
exclude = [".idea/*", ".gitignore", "files.gif", "mdedit.gif"]

[features]
default = []
async = ["dep:tokio"]

[dependencies]
crossbeam = "0.8"
crossterm = "0.28"
log = "0.4"
ratatui = { version = "0.29" }
tokio = { version = "1.42", features = ["rt", "rt-multi-thread", "sync", "time"], optional = true }

rat-widget = { version = "0.33", path = "../rat-widget" }

[dev-dependencies]
fern = "0.7"
humantime = "2.1"
anyhow = "1.0"
directories-next = "2.0"
sysinfo = "0.33"
pulldown-cmark = "0.12"
ropey = "1.6"
cli-clipboard = "0.4"
unicode-segmentation = "1.11"
textwrap = "0.16"
configparser = { version = "3.1", features = ["indexmap"] }
rand = "0.8"

rat-theme = { version = "0.27", path = "../rat-theme" }


[[example]]
name = "async1"
required-features = ["async"]